# Generated by Django 4.2 on 2023-04-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(default=' ', max_length=300),
            preserve_default=False,
        ),
    ]
