# Generated by Django 4.2 on 2023-05-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_produit_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(default=' ', max_length=288),
            preserve_default=False,
        ),
    ]
