# Generated by Django 4.2 on 2023-05-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_produit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='slug',
            field=models.SlugField(default='abcd'),
        ),
    ]
