# Generated by Django 4.2 on 2023-05-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_produit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='slug',
            field=models.SlugField(blank=True, default='abcd', null=True),
        ),
    ]
