# Generated by Django 4.2.2 on 2023-06-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_produit_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
    ]
